### ISSUE TITLE
Ceiling not adding one interval if date is exactly the beginning of the interval.

### ISSUE THREAD

**Issue by bChiquet** [justinmimbs/elm-date-extra#8]
Currently using Ceiling on a date may yield either the next interval beginning, or, if the date is the exact beginning of an interval, itself. From reading the code, this seems to be voluntary.

However, this violates some desirable invariants of the code: e.g. for any `date`, one would expect that the duration between `floor interval date` and `ceiling interval date` is always one `interval`.

What do you think?

**Comment by justinmimbs** [comment]
Hi there,

As you noted, this is intentional, as it's [how ceiling works on numbers](https://en.wikipedia.org/wiki/Floor_and_ceiling_functions) too (e.g. `ceiling 2.0 == 2`).

If you're looking for a way to always return a future date, you could `floor` the date and then `add` the appropriate intervals.

```elm
nextSaturday : Date -> Date
nextSaturday =
    floor Saturday >> add Week 1
```

Does this help?

Justin

**Comment by bChiquet** [comment]
Yes, thanks. That's what we currently do, but your formulation is actually better :+1:
