### ISSUE TITLE
Upgrade to Elm 0.19

### ISSUE THREAD

**Issue by thitemple** [justinmimbs/elm-date-extra#9]
Hi, I'm working on an upgrade for this to Elm 0.19, the thing is now I'm stuck with the fact that a lot of new functions such as `toMinute`, `toYear` and so on expect a `Zone` as [you can see in the docs](https://package.elm-lang.org/packages/elm/time/latest/Time#toMinute). 

What would you like to be done? Ask that information from the consumer of the package? I think this is the safest choice, the other option would be to use [here](https://package.elm-lang.org/packages/elm/time/latest/Time#here)

**Comment by justinmimbs** [comment]
Hi Thiago,

Thanks for your interest! I don't think this package needs to be upgraded to 0.19, at least not directly, since the `Date` type it supports in 0.18 doesn't exist in 0.19. A big use of this package, as far as I can tell, is for converting ISO 8601 strings in UTC time to display strings in the client's local time. There already exist 0.19 packages for [converting UTC ISO 8601 strings](https://package.elm-lang.org/packages/rtfeldman/elm-iso8601-date-strings/latest/) to `Posix` and for [formatting](https://package.elm-lang.org/packages/ryannhg/date-format/latest/) `Posix` to strings given a `Zone`. I think there's a gap where `Zone` data is concerned, and for that you might look into [these approaches](https://discourse.elm-lang.org/t/time-zone-explorations/1837).

This package also offers operations like `add`, `diff`, and `floor`; I found that I mainly used such functions on the date parts of `Date`, and not the time parts. So for working with just calendar dates in 0.19, I've published a [date package](https://package.elm-lang.org/packages/justinmimbs/date/latest/) with a `Date` type that doesn't include notions of time or zone. That leaves a gap for functions that operate on the time parts of a `Posix`, and I think that could be done in its own library, which would be more narrow in scope than this one.

I hope this makes sense!

Thanks,

Justin

**Comment by thitemple** [comment]
It makes, TBH I was working on this library because when I tried to upgrade another library `elm-upgrade` stated that this library has not yet been upgraded. I'm going to check what are the uses that 
other library makes of this one.

In any case, the work I did so far was actually to use `Posix` and what comes with it. There was also a couple of issues with `Regex` that are now fixed.

**Comment by justinmimbs** [comment]
Hi @thitemple, to follow up, I do plan to publish a package soon containing those extra functions that I think are currently missing for `Posix`, like `add`, `diff`, `range`, etc. I wanted to let you know in case this will unblock other work for you. It's currently at [`time-extra`](https://github.com/justinmimbs/time-extra), and the functions are ported and tested, but I haven't yet published it. In the meantime, I'm open to breaking changes, so please let me know if you have any feedback. Thanks!

**Comment by justinmimbs** [comment]
The following functions from `elm-date-extra` have been ported to [`justinmimbs/time-extra`](https://package.elm-lang.org/packages/justinmimbs/time-extra/latest/):

- `add`, `diff`, `floor`, `ceiling`, `range`, `partsToPosix` (previously `fromParts`), `toOffset` (previously `offsetFromUtc`)

All functions now take a `Zone` before the `Posix`. The only other change is that `diff` now returns the inverse of what it used to, so to migrate usage of `diff`, just swap the two time arguments.

If you have any feedback, please feel free to open an issue on [`time-extra`](https://github.com/justinmimbs/time-extra) to discuss!
